#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index
