#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index

survey_list:
  path: /api/survey
  methods: [GET]
  controller: App\Controller\SurveyController::list

survey_show:
  path: /api/survey/{id}
  methods: [GET]
  controller: App\Controller\SurveyController::show
  requirements:
      id: '\d+'

survey_create:
  path: /api/survey/create
  methods: [POST]
  controller: App\Controller\SurveyController::create

survey_update:
  path: /api/survey/update/{id}
  methods: [PUT]
  controller: App\Controller\SurveyController::update
  requirements:
    id: '\d+'

survey_delete:
  path: /api/survey/delete/{id}
  methods: [DELETE]
  controller: App\Controller\SurveyController::delete
  requirements:
    id: '\d+'

survey_list_questions:
  path: /api/survey/list-questions/{id}
  methods: [GET]
  controller: App\Controller\SurveyController::listQuestions
  requirements:
    id: '\d+'

survey_send_answers:
  path: /api/survey/send-answers/{id}
  methods: [POST]
  controller: App\Controller\SurveyController::sendAnswers
  requirements:
    id: '\d+'

survey_list_answer_groups:
  path: /api/survey/list-answers/{id}
  methods: [GET]
  controller: App\Controller\SurveyController::listAnswerGroups
  requirements:
    id: '\d+'

question_show:
  path: /api/question/{id}
  methods: [GET]
  controller: App\Controller\QuestionController::show
  requirements:
      id: '\d+'

question_create:
  path: /api/question/create
  methods: [POST]
  controller: App\Controller\QuestionController::create

question_update:
  path: /api/question/update/{id}
  methods: [PUT]
  controller: App\Controller\QuestionController::update
  requirements:
    id: '\d+'

question_delete:
  path: /api/question/delete/{id}
  methods: [DELETE]
  controller: App\Controller\QuestionController::delete
  requirements:
    id: '\d+'

question_list_options:
  path: /api/question/list-options/{id}
  methods: [DELETE]
  controller: App\Controller\QuestionController::listOptions
  requirements:
    id: '\d+'

option_show:
  path: /api/option/{id}
  methods: [GET]
  controller: App\Controller\OptionController::show
  requirements:
      id: '\d+'

option_create:
  path: /api/option/create
  methods: [POST]
  controller: App\Controller\OptionController::create

option_update:
  path: /api/option/update/{id}
  methods: [PUT]
  controller: App\Controller\OptionController::update
  requirements:
    id: '\d+'

option_delete:
  path: /api/option/delete/{id}
  methods: [DELETE]
  controller: App\Controller\OptionController::delete
  requirements:
    id: '\d+'