#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\RegistrationController::index

survey_list:
  path: /api/survey
  methods: [GET]
  controller: App\Controller\SurveyController::list

survey_show:
  path: /api/survey/{id}
  methods: [GET]
  controller: App\Controller\SurveyController::show
  requirements:
      id: '\d+'

survey_create:
  path: /api/survey/create
  methods: [POST]
  controller: App\Controller\SurveyController::create

survey_update:
  path: /api/survey/update/{id}
  methods: [PUT]
  controller: App\Controller\SurveyController::update
  requirements:
    id: '\d+'

survey_delete:
  path: /api/survey/delete/{id}
  methods: [DELETE]
  controller: App\Controller\SurveyController::delete
  requirements:
    id: '\d+'

question_list:
  path: /api/question/list/{id}
  methods: [GET]
  controller: App\Controller\QuestionController::list
  requirements:
    id: '\d+'

question_show:
  path: /api/question/{id}
  methods: [GET]
  controller: App\Controller\QuestionController::show
  requirements:
      id: '\d+'

question_create:
  path: /api/question/create
  methods: [POST]
  controller: App\Controller\QuestionController::create

question_update:
  path: /api/question/update/{id}
  methods: [PUT]
  controller: App\Controller\QuestionController::update
  requirements:
    id: '\d+'

question_delete:
  path: /api/question/delete/{id}
  methods: [DELETE]
  controller: App\Controller\QuestionController::delete
  requirements:
    id: '\d+'